[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

[etherscan]
avalanche_fuji = { key = "${SNOWTRACE_API_KEY}" }

[rpc_endpoints]
fuji = "${FUJI_RPC}"

[fmt]
line_length = 100
